"use client";

import "./globals.scss";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "./navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  );
}
